#! /usr/bin/env perl

use strict;
use warnings;
use 5.010;

use Test::Code::TidyAll 0.24;
use Test::More 0.88;

## tidyall_ok();
tidyall_ok( conf_file => 'tidyall.ini' );

done_testing();

__END__

=head1 NAME

xt/release/tidyall.t - Test that tidyall runs without error

=head1 PURPOSE

=head2 What code?

Varies; selected by the tidyall config, either the default as searched for
by Code::TidyAll, or if needed, hard-coded for this test.

=head2 When?

At release time. This is a QA test, runtime behavior is not affected. Only the
parts of the tidyall config that run during mode=test are run.

=head2 Purpose?

To run tidyall in test mode, which will run tests as configured, especially
perlcritic.

=head2 Why?

Tidyal wrapps multiple code checkers and testers in one interface. This test
exists to use that interface automatically at release time to insure that
all tests run by Tidyall pass. You did run this manually and verify it before
trying to release, right? Then this should produce no surprises.

=head1 INTERNALS

Based on the test file generated by Dist::Zilla::Plugin::Test::TidyAll, but
hardcoding the config file name (if needed) rather than generating the test at
build-time. Modification to use other parts of Code::TidyAll, e.g. to seach for
a named config file rather than using the name as given, are also possible.

This test always runs as check-only and in test mode.

=cut
